<a href="https://colab.research.google.com/github/Nguyen-Quoc-An/TH_DeepLearning/blob/main/Buoi1_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY



In [41]:
import numpy as np
# cách 1
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [42]:
c = np.array([(1, 2, 3),
              (4, 5, 6)
             ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [43]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [44]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [45]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
# Thay đổi về kích thước 3 hàng, 2 cột
f = e.reshape(3, 2)
print(f)
# Với mảng 3 chiều
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [46]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [47]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
# Nối ngang
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
# Nối dọc
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [48]:
# Sinh mảng 1 chiều
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
# Sinh mảng 2 chiều
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
# Sinh mảng 3 chiều
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [18  2 18 38 70]
Random 2-D array
 [[86 37 63 37]
 [18 41 19  3]
 [40 79 70  1]]
Random 3-D array
 [[[83 44 70]
  [80 84 66]
  [87 24 69]
  [11 54 20]]

 [[94 18 28]
  [95 91 55]
  [37 50 81]
  [75 43  4]]

 [[13 40 93]
  [83 38 59]
  [ 7 41 71]
  [37 59 82]]]


In [49]:
# Sinh mảng 1 chiều
a = np.random.rand(5)
print('Random 1-D array\n', a)
# Sinh mảng 2 chiều
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
# Sinh mảng 3 chiều
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.98354496 0.50641592 0.28534828 0.18461379 0.77463662]
Random 2-D array
 [[0.13963842 0.41446776 0.06507641 0.27954104]
 [0.50144619 0.5937103  0.06816548 0.45836925]
 [0.08846069 0.630364   0.02725259 0.47267536]]
Random 3-D array
 [[[0.4938248  0.48682772 0.84587374]
  [0.00833695 0.79317045 0.35131085]
  [0.92026814 0.06188046 0.70257556]
  [0.05195386 0.78470443 0.35066553]]

 [[0.11683721 0.86271487 0.60920845]
  [0.05292747 0.0727046  0.48584695]
  [0.16021443 0.18166006 0.79100467]
  [0.92297876 0.84846113 0.83974042]]

 [[0.92932952 0.363563   0.14491709]
  [0.9535444  0.34740237 0.54165846]
  [0.06808215 0.5260438  0.83130704]
  [0.97967618 0.22059053 0.28561343]]]


In [50]:
# Sinh 10 số với trung bình là 5 và độ lệch chuẩn là 0.5
a = np.random.normal(5, 0.5, 10)
print(a)

[4.95890252 5.11999326 5.09800253 5.25478905 4.92110264 5.10016318
 4.05250873 5.02749496 4.99820367 4.50691301]


In [51]:
# sinh 1 giá trị ngẫu nhiên
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
# sinh ma trận 3 x 5 ngẫu nhiên
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

10
[[ 8 20 20 20 12]
 [ 6 14  8  4  2]
 [10  4 10  8  4]]


In [52]:
# Tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
# tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)
# tạo số nguyên từ 1 --> 19, mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [54]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [55]:
# slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
# indexing
print('Second column:', a[:, 1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


#PANDAS


In [56]:
pip install pandas

In [57]:
import pandas as pd
# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
# Tạo series với chỉ số (index) tùy chỉnh
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [58]:
# NumPy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)
# Pandas --> NumPy
numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [59]:
# Từ Dictionary
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)
# Từ mảng ngẫu nhiên (20 hàng x 4 cột)
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0 -0.863399  0.424080 -1.455318 -0.389486
1  0.830942  0.688986  1.231398 -0.888144
2 -1.099658  0.367244  1.082489  1.139922
3  0.723129  1.835389 -1.051856  0.385849
4 -0.796568 -2.063284  0.897130 -0.957670


In [60]:
# Tạo mảng ngẫu nhiên 20 x 4 để thực hành
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())
print('Chọn cột so1\n', df['so1'])
# Chọn nhiều dòng (từ dòng 0 đến dòng 2)
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
# Lấy 3 dòng đầu và 2 cột đầu
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])
# Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0  1.550879 -0.114711  0.435218 -0.940134
1  0.983199 -0.477427  1.556992 -0.424481
2 -0.054505  1.220412  0.587467 -0.483047
3 -0.758656  0.485096 -0.854702  1.706209
4 -0.145591  1.069398  0.765691  2.649206
Chọn cột so1
 0     1.550879
1     0.983199
2    -0.054505
3    -0.758656
4    -0.145591
5     1.540716
6     0.318047
7    -0.581110
8    -0.700833
9    -0.708830
10    0.731683
11   -0.823274
12   -0.693638
13    0.294078
14   -0.220959
15    0.688699
16    0.460875
17    0.211854
18   -1.352882
19   -0.471090
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  1.550879 -0.114711  0.435218 -0.940134
1  0.983199 -0.477427  1.556992 -0.424481
2 -0.054505  1.220412  0.587467 -0.483047
Chọn nhiều cột
          so1       so3
0   1.550879  0.435218
1   0.983199  1.556992
2  -0.054505  0.587467
3  -0.758656 -0.854702
4  -0.145591  0.765691
5   1.540716 -0.665210
6   0.318047  0.692695
7  -0.581110  1.319456


In [61]:
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])
# Nối 2 DataFrame
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))
# Sắp xếp dữ liệu theo cột (theo tuổi)
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))
# Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [62]:
import pandas as pd
data = {
    'YearsExperience': [1.1, 1.3, 1.5, 2.0, 2.2, 2.9, 3.0, 3.2, 3.2, 3.7],
    'Salary': [39343, 46205, 37731, 43525, 39891, 56642, 60150, 54445, 64445, 57189]
}
df_temp = pd.DataFrame(data)
df_temp.to_csv('/content/sample_data/Salary_Data.csv', index=False)
print("Đã tạo file Salary_Data.csv thành công!")

Đã tạo file Salary_Data.csv thành công!


In [63]:
path = '/content/sample_data/Salary_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']
# Cách 1: Gán tên cột thủ công
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
# Cách 2: Sử dụng header có sẵn trong file
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

   YearsExperience  Salary
0  YearsExperience  Salary
1              1.1   39343
2              1.3   46205
3              1.5   37731
4              2.0   43525
(11, 2)
   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
(10, 2)


In [64]:
import pandas as pd
fish_data = {
    'Species': ['Bream', 'Bream', 'Bream', 'Roach', 'Roach', 'Pike', 'Pike', 'Perch', 'Perch', 'Parkki'],
    'Weight': [242.0, 290.0, 340.0, 120.0, 150.0, 200.0, 300.0, 5.9, 100.0, 55.0],
    'Length1': [23.2, 24.0, 23.9, 19.0, 20.0, 30.0, 35.0, 7.5, 15.0, 13.5],
    'Length2': [25.4, 26.3, 26.5, 21.0, 22.0, 32.3, 37.0, 8.4, 16.5, 14.7],
    'Length3': [30.0, 31.2, 31.1, 22.5, 23.5, 34.8, 40.0, 8.8, 18.2, 16.5],
    'Height': [11.52, 12.48, 12.37, 5.85, 6.11, 5.57, 7.21, 2.11, 4.01, 3.5],
    'Width': [4.02, 4.31, 4.69, 3.52, 3.72, 3.37, 4.56, 1.41, 2.82, 2.5]
}
df_fish = pd.DataFrame(fish_data)
df_fish.to_csv('/content/sample_data/Fish.csv', index=False)
print("Đã 'thả' cá vào file /content/sample_data/Fish.csv thành công!")

Đã 'thả' cá vào file /content/sample_data/Fish.csv thành công!


In [65]:
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

             Weight  Length1    Length2    Length3     Height  Width
Species                                                             
Bream    290.666667    23.70  26.066667  30.766667  12.123333  4.340
Parkki    55.000000    13.50  14.700000  16.500000   3.500000  2.500
Perch     52.950000    11.25  12.450000  13.500000   3.060000  2.115
Pike     250.000000    32.50  34.650000  37.400000   6.390000  3.965
Roach    135.000000    19.50  21.500000  23.000000   5.980000  3.620
Species
Bream     242.0
Parkki     55.0
Perch       5.9
Pike      200.0
Roach     120.0
Name: Weight, dtype: float64
Species  Height
Bream    11.52     242.0
         12.37     340.0
         12.48     290.0
Parkki   3.50       55.0
Perch    2.11        5.9
Name: Weight, dtype: float64


#TENSORFLOW


In [66]:
import tensorflow as tf
import numpy as np

In [67]:
# 0-chiều (scalar)
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
r1_float = tf.constant(1.12, tf.float32)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1); print(r1_float); print(r1_string)
# 1-chiều (vector)
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)
# 2-chiều (ma trận)
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)
# 3-chiều
rank_3_tensor = tf.constant([
  [[0,1,2,3,4],[5,6,7,8,9]],
  [[10,11,12,13,14],[15,16,17,18,19]],
  [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [68]:
# zeros
t_zero = tf.zeros(10);        print(t_zero)
t_2zero = tf.zeros([3,3]);    print(t_2zero)
t_3zero = tf.zeros([3,3,5]);  print(t_3zero)
# ones
t_one  = tf.ones(10);         print(t_one)
t_2one = tf.ones([3,3]);      print(t_2one)
t_3one = tf.ones([3,3,5]);    print(t_3one)
# fill (giá trị bất kỳ)
t_1 = tf.fill(3, 10);       print(t_1)
t_2 = tf.fill([3,3], 9);    print(t_2)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)
tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [69]:
# linspace — số phần tử cố định trong khoảng
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)
# range — bước nhảy delta
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)
range_tensor2 = tf.range(3.0, delta=0.5)
print(range_tensor2)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)
tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [70]:
# normal
rt = tf.random.normal([5]);    print(rt)
rt = tf.random.normal([3,3]);  print(rt)
# truncated_normal
rt = tf.random.truncated_normal([5]);   print(rt)
rt = tf.random.truncated_normal([3,2]); print(rt)
rt = tf.random.truncated_normal([3,2,2]); print(rt)
# uniform
rt = tf.random.uniform([5], minval=10, maxval=20);      print(rt)
rt = tf.random.uniform([3,2], minval=10, maxval=20);    print(rt)
rt = tf.random.uniform([3,2,5], minval=10, maxval=20);  print(rt)
# shuffle
rt = tf.random.uniform([5], minval=10, maxval=20)
print(rt)
print(tf.random.shuffle(rt))

tf.Tensor([ 0.15140589  0.3868447   0.49444622 -0.02442385  0.7136153 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 1.0116857   0.79632616  0.9100304 ]
 [ 0.5619967  -0.93627214  1.8106682 ]
 [-0.61821467  1.2648247   0.09137807]], shape=(3, 3), dtype=float32)
tf.Tensor([-1.7694083  -0.52085674 -0.97418964 -0.56258726  0.26674998], shape=(5,), dtype=float32)
tf.Tensor(
[[-1.5355175   0.72912174]
 [ 1.5751371  -0.78953016]
 [ 0.38819233 -1.8710635 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[ 0.13203433 -1.5329673 ]
  [ 1.6890227  -0.32460058]]

 [[ 0.8632438   0.3154215 ]
  [ 0.30589163 -0.9342616 ]]

 [[-0.46751404  1.0955058 ]
  [ 0.10356059 -0.8492112 ]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor([12.809648 16.455614 10.184177 14.757185 19.087433], shape=(5,), dtype=float32)
tf.Tensor(
[[15.997189  10.2156315]
 [19.452179  17.132273 ]
 [17.946926  15.093971 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[16.976763 11.815285 13.223497 15.888929 12.792016]
  [10.635801 11.889319 16.88

#BÀI TẬP NUMPY_PANDAS_LAB1


In [71]:
#1.Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)
import numpy as np
arr1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 1:\n", arr1)
check_all = np.all(arr1 != 0)
print("Tất cả phần tử đều khác 0?", check_all)

Mảng 1:
 [[11 18 13]
 [10  2 10]
 [ 3  2 19]]
Tất cả phần tử đều khác 0? True


In [72]:
#2.Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)
arr2 = np.random.randint(0, 21, size=(3, 3))
print("\nMảng 2:\n", arr2)
check_any = np.any(arr2 != 0)
print("Có tồn tại phần tử khác 0?", check_any)


Mảng 2:
 [[13 15  2]
 [ 0 15 10]
 [18 14  5]]
Có tồn tại phần tử khác 0? True


In [73]:
#3.Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater, numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.
x = np.array([5, 10])
y = np.array([5, 8])
print("\nSo sánh mảng:")
print("Lớn hơn (x > y):", np.greater(x, y))
print("Lớn hơn hoặc bằng (x >= y):", np.greater_equal(x, y))
print("Nhỏ hơn (x < y):", np.less(x, y))
print("Nhỏ hơn hoặc bằng (x <= y):", np.less_equal(x, y))


So sánh mảng:
Lớn hơn (x > y): [False  True]
Lớn hơn hoặc bằng (x >= y): [ True  True]
Nhỏ hơn (x < y): [False False]
Nhỏ hơn hoặc bằng (x <= y): [ True False]


In [74]:
#4.Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.ones(10) * 5
arr_noi = np.hstack((ones, zeros, fives))
print("\nMảng kết hợp:\n", arr_noi)


Mảng kết hợp:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [75]:
#5.Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]
mang_chan = np.arange(30, 71, 2)
print("\nMảng số chẵn từ 30 đến 70:\n", mang_chan)


Mảng số chẵn từ 30 đến 70:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [76]:
#6.Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)(Tìm hiểu hàm identity của numpy)
ma_tran_don_vi = np.identity(3)
print("\nMa trận đơn vị 3x3:\n", ma_tran_don_vi)


Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
#7.Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử đầu và cuối
arr = np.random.randint(15, 56, 10)
print("Mảng ban đầu:", arr)
print("Kết quả (trừ đầu và cuối):", arr[1:-1])

Mảng ban đầu: [44 24 23 18 54 55 51 29 50 53]
Kết quả (trừ đầu và cuối): [24 23 18 54 55 51 29 50]


In [78]:
#8.Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong khoảng [9, 15]
arr = np.random.randint(0, 21, 20)
print("Trước khi đổi dấu:", arr)
arr[(arr >= 9) & (arr <= 15)] *= -1
print("Sau khi đổi dấu:", arr)

Trước khi đổi dấu: [ 7 15  7 11 18 14 13 18 12 15  1 20 13  2 10 13 17  2  7 20]
Sau khi đổi dấu: [  7 -15   7 -11  18 -14 -13  18 -12 -15   1  20 -13   2 -10 -13  17   2
   7  20]


In [79]:
#9.Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]
matrix_3x4 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:\n", matrix_3x4)

Ma trận 3x4:
 [[14 11 20 17]
 [20 16 11 21]
 [18 20 10 19]]


In [80]:
#10.Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có giá trị 0
arr_border = np.ones((10, 10))
arr_border[1:-1, 1:-1] = 0
print("Ma trận viền 1:\n", arr_border)

Ma trận viền 1:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [81]:
#11.Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu hàm diag của numpy)
diag_matrix = np.diag([1, 2, 3, 4, 5])
print("Ma trận đường chéo:\n", diag_matrix)

Ma trận đường chéo:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [82]:
#12.Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum của numpy)
arr_3d = np.random.randint(1, 10, size=(3, 3, 3))
print("Mảng 3D:\n", arr_3d)
sum_rows = np.sum(arr_3d, axis=1)
sum_cols = np.sum(arr_3d, axis=2)
print("\nTổng theo mỗi dòng của từng lớp:\n", sum_rows)
print("\nTổng theo mỗi cột của từng lớp:\n", sum_cols)

Mảng 3D:
 [[[8 6 9]
  [1 8 7]
  [4 3 5]]

 [[9 4 3]
  [3 8 7]
  [2 8 4]]

 [[4 6 6]
  [1 6 8]
  [1 7 9]]]

Tổng theo mỗi dòng của từng lớp:
 [[13 17 21]
 [14 20 14]
 [ 6 19 23]]

Tổng theo mỗi cột của từng lớp:
 [[23 16 12]
 [16 18 14]
 [16 15 17]]


In [83]:
#13.Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)
v1 = np.random.rand(10)
v2 = np.random.rand(10)
result_dot = np.dot(v1, v2)
print("Vector 1:", v1)
print("Vector 2:", v2)
print("Kết quả tích vô hướng:", result_dot)

Vector 1: [0.76644888 0.92297575 0.93519247 0.84522943 0.29292042 0.73250905
 0.84539728 0.60926465 0.1568119  0.9596374 ]
Vector 2: [0.06027623 0.6764909  0.97903408 0.54127875 0.43207306 0.04956903
 0.07990017 0.24430099 0.12319579 0.44808769]
Kết quả tích vô hướng: 2.8722577840276364


In [84]:
#14.Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của ma trận A
A = np.random.randint(1, 10, (4, 3))
y = np.array([10, 20, 30])
result_add = A + y
print("Ma trận A:\n", A)
print("Vector y:", y)
print("Kết quả sau khi cộng:\n", result_add)

Ma trận A:
 [[7 8 7]
 [7 3 9]
 [3 2 2]
 [1 6 9]]
Vector y: [10 20 30]
Kết quả sau khi cộng:
 [[17 28 37]
 [17 23 39]
 [13 22 32]
 [11 26 39]]


In [85]:
#15.Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])
print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [86]:
#16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series (Tìm hiểu thuộc tính ix của pandas)
data = {
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
}
df = pd.DataFrame(data)
s = df.iloc[:, 0]
print("1st column as a Series:")
print(s)

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [87]:
#17. Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)),
                  columns=['col1', 'col2', 'col3'])
print("DataFrame ban đầu:\n", df)
df_sorted = df.sort_values(by='col1')
print("\nDataFrame sau khi sắp xếp theo cột 'col1':\n", df_sorted)

DataFrame ban đầu:
    col1  col2  col3
0    46    93    99
1    10    85     8
2    77    20    69
3     6    32    94

DataFrame sau khi sắp xếp theo cột 'col1':
    col1  col2  col3
3     6    32    94
1    10    85     8
0    46    93    99
2    77    20    69


In [88]:
#18. Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex)
s = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Series ban đầu:")
print(s)
new_order = ['B', 'A', 'C', 'D', 'E']
s_reindexed = s.reindex(new_order)
print("\n Series sau khi thực hiện reindex:")
print(s_reindexed)

Series ban đầu:
A    1
B    2
C    3
D    4
E    5
dtype: int64

 Series sau khi thực hiện reindex:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [89]:
#19. Viết chương trình Pandas tìm những phần tử trong Series x mà không có trong Series y (Sử dụng hàm isin)
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
result = sr1[~sr1.isin(sr2)]
print("sr1:")
print(sr1)
print("\nsr2:")
print(sr2)
print("\nItems of sr1 not present in sr2:")
print(result)

sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64

sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


In [90]:
#20. Tìm hiểu phép toán numpy.union1d và numpy.intersect1d trên 2 Series ngẫu nhiên
x = pd.Series(np.random.randint(1, 31, 20))
y = pd.Series(np.random.randint(1, 31, 20))
hội = np.union1d(x, y)
giao = np.intersect1d(x, y)
print("Series x:\n", x.values)
print("\nSeries y:\n", y.values)
print("\nHội (Tất cả phần tử duy nhất từ cả hai):\n", hội)
print("\nGiao (Các phần tử xuất hiện ở cả hai):\n", giao)

Series x:
 [27  4 25  7 10 12 11 27  1 22 25 12 23 26  4  6  4 28 12  2]

Series y:
 [ 8 13 10 15 10 23  8 20  2  9 27  2  1  4  5 22 25 18 23 21]

Hội (Tất cả phần tử duy nhất từ cả hai):
 [ 1  2  4  5  6  7  8  9 10 11 12 13 15 18 20 21 22 23 25 26 27 28]

Giao (Các phần tử xuất hiện ở cả hai):
 [ 1  2  4 10 22 23 25 27]


In [91]:
#21. Viết chương trình Pandas thêm series y vào series x theo chiều dọc (vertical), chiều ngang (horizontal) (Tìm hiểu hàm append và concat của pandas)
x = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'])
vertical = pd.concat([x, y], ignore_index=True)
horizontal = pd.concat([x, y], axis=1)
print("Thêm series y vào series x theo chiều dọc (vertical):")
print(vertical)
print("\nThêm series y vào series x theo chiều ngang (horizontal):")
print(horizontal)

Thêm series y vào series x theo chiều dọc (vertical):
0     0
1     1
2     2
3     3
4     4
5     5
6     6
7     7
8     8
9     9
10    p
11    q
12    r
13    s
14    t
15    u
16    v
17    w
18    x
19    y
dtype: object

Thêm series y vào series x theo chiều ngang (horizontal):
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [92]:
#22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame sau
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [93]:
#23. Từ bài 22, cho biết 3 dòng đầu tiên
print(df.head(3))

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [94]:
#24. Từ bài 22, chọn cột ‘name’ và ‘score’
print(df[['name', 'score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [95]:
#25. Từ bài 22, chọn những dòng có attempts > 2
print(df[df['attempts'] > 2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [96]:
#26. Từ bài 22, cho biết số dòng, số cột của DataFrame
print("Số dòng và số cột:", df.shape)

Số dòng và số cột: (10, 4)


In [97]:
#27. Từ bài 22, cho biết những dòng có score là NaN (tìm hiểu hàm isnull của pandas)
print(df[df['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [98]:
#28. Từ bài 22, cho biết những dòng có score trong khoảng (15, 20) (tìm hiểu hàm between của pandas)
print(df[df['score'].between(15, 20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


In [99]:
#29. Từ bài 22, cho biết những dòng có attempt > 2 và score trong khoảng (15, 20)
print(df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

      name  score  attempts qualify
f  Michael   20.0         3     yes


In [100]:
#30. Từ bài 22, cho biết những thay đổi giá trị dòng ‘d’, cột score là 19 (tìm hiểu hàm loc của pandas)
df.loc['d', 'score'] = 19
print("Dữ liệu sau khi thay đổi tại dòng 'd':")
print(df.loc[['d']])

Dữ liệu sau khi thay đổi tại dòng 'd':
    name  score  attempts qualify
d  James   19.0         3      no
