<a href="https://colab.research.google.com/github/Nguyen-Quoc-An/TH_DeepLearning/blob/main/Buoi1_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY



In [36]:
import numpy as np
# cách 1
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [37]:
c = np.array([(1, 2, 3),
              (4, 5, 6)
             ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [38]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [39]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [40]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
# Thay đổi về kích thước 3 hàng, 2 cột
f = e.reshape(3, 2)
print(f)
# Với mảng 3 chiều
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)
j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)
k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [41]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [42]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
# Nối ngang
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)
# Nối dọc
v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [43]:
# Sinh mảng 1 chiều
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
# Sinh mảng 2 chiều
b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
# Sinh mảng 3 chiều
c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [64 64 96 86 54]
Random 2-D array
 [[82  0 97 28]
 [88 85 47 73]
 [24  7 67 21]]
Random 3-D array
 [[[51 64 94]
  [66 55 14]
  [95 62 60]
  [60  6 23]]

 [[39 84 81]
  [60 14 58]
  [42 80 66]
  [34 11 14]]

 [[85  4 32]
  [13 30  4]
  [59 54 71]
  [74 39 77]]]


In [44]:
# Sinh mảng 1 chiều
a = np.random.rand(5)
print('Random 1-D array\n', a)
# Sinh mảng 2 chiều
b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
# Sinh mảng 3 chiều
c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.91801561 0.91067237 0.3834955  0.42655579 0.11827127]
Random 2-D array
 [[0.36613247 0.68271462 0.97445781 0.47087302]
 [0.9791548  0.17110835 0.52466778 0.27956467]
 [0.45431375 0.46426334 0.56840923 0.26785292]]
Random 3-D array
 [[[0.57522943 0.56716356 0.15792328]
  [0.5584807  0.31967191 0.68681136]
  [0.617084   0.51962271 0.22292511]
  [0.2954582  0.36165676 0.72280807]]

 [[0.4125528  0.59334979 0.75930109]
  [0.66611642 0.24749802 0.36986294]
  [0.57801319 0.04373776 0.83421354]
  [0.79429172 0.58686311 0.68833646]]

 [[0.54783603 0.00566714 0.90850784]
  [0.82385384 0.75724639 0.45944599]
  [0.23325308 0.51711269 0.90335335]
  [0.66421066 0.12114501 0.29855955]]]


In [45]:
# Sinh 10 số với trung bình là 5 và độ lệch chuẩn là 0.5
a = np.random.normal(5, 0.5, 10)
print(a)

[4.95396773 4.72609856 4.11541834 4.6841829  5.55237813 5.0031761
 5.43273425 5.63856243 4.97345519 5.24168844]


In [46]:
# sinh 1 giá trị ngẫu nhiên
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)
# sinh ma trận 3 x 5 ngẫu nhiên
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

2
[[ 4  8 20 12  8]
 [18  4  2  8 10]
 [12 20 18  2  2]]


In [47]:
# Tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
# tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)
# tạo số nguyên từ 1 --> 19, mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [49]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [50]:
# slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])
# indexing
print('Second column:', a[:, 1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


#PANDAS


In [51]:
pip install pandas

In [52]:
import pandas as pd
# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])
# Tạo series với chỉ số (index) tùy chỉnh
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])
# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [53]:
# NumPy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)
# Pandas --> NumPy
numpy_h = np.array(df_h)
print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [54]:
# Từ Dictionary
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)
# Từ mảng ngẫu nhiên (20 hàng x 4 cột)
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())

    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  0.009356 -1.186712  1.422154 -1.052866
1  0.606380  0.213245  1.283675  1.166169
2  0.236106  0.827380 -0.450086 -1.182963
3  0.519711  0.292051 -1.204391 -0.119102
4  0.151022 -0.723633  0.746388 -0.128942


In [55]:
# Tạo mảng ngẫu nhiên 20 x 4 để thực hành
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())
print('Chọn cột so1\n', df['so1'])
# Chọn nhiều dòng (từ dòng 0 đến dòng 2)
print('Chọn nhiều dòng\n', df[0:3])
print('Chọn nhiều cột\n', df[['so1', 'so3']])
# Lấy 3 dòng đầu và 2 cột đầu
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])
# Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -0.565692 -0.647273  0.521999 -0.974670
1  0.257931 -0.651952 -0.629177  0.958396
2 -0.086938  0.646302  0.006988 -2.330263
3  2.118631 -0.636692 -1.208652 -0.378113
4  1.862681  0.030282 -0.750126 -1.571896
Chọn cột so1
 0    -0.565692
1     0.257931
2    -0.086938
3     2.118631
4     1.862681
5     1.375031
6     0.579645
7     0.471108
8     1.651955
9    -0.496892
10   -0.913184
11   -1.022529
12   -0.456209
13   -1.250332
14   -1.258928
15    0.323263
16   -0.529635
17    1.110964
18   -0.259712
19   -0.569129
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.565692 -0.647273  0.521999 -0.974670
1  0.257931 -0.651952 -0.629177  0.958396
2 -0.086938  0.646302  0.006988 -2.330263
Chọn nhiều cột
          so1       so3
0  -0.565692  0.521999
1   0.257931 -0.629177
2  -0.086938  0.006988
3   2.118631 -1.208652
4   1.862681 -0.750126
5   1.375031  1.525528
6   0.579645  0.602262
7   0.471108  0.389877


In [56]:
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])
# Nối 2 DataFrame
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))
# Sắp xếp dữ liệu theo cột (theo tuổi)
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))
# Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [57]:
import pandas as pd
data = {
    'YearsExperience': [1.1, 1.3, 1.5, 2.0, 2.2, 2.9, 3.0, 3.2, 3.2, 3.7],
    'Salary': [39343, 46205, 37731, 43525, 39891, 56642, 60150, 54445, 64445, 57189]
}
df_temp = pd.DataFrame(data)
df_temp.to_csv('/content/sample_data/Salary_Data.csv', index=False)
print("Đã tạo file Salary_Data.csv thành công!")

Đã tạo file Salary_Data.csv thành công!


In [58]:
path = '/content/sample_data/Salary_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']
# Cách 1: Gán tên cột thủ công
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
# Cách 2: Sử dụng header có sẵn trong file
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

   YearsExperience  Salary
0  YearsExperience  Salary
1              1.1   39343
2              1.3   46205
3              1.5   37731
4              2.0   43525
(11, 2)
   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
(10, 2)


In [59]:
import pandas as pd
fish_data = {
    'Species': ['Bream', 'Bream', 'Bream', 'Roach', 'Roach', 'Pike', 'Pike', 'Perch', 'Perch', 'Parkki'],
    'Weight': [242.0, 290.0, 340.0, 120.0, 150.0, 200.0, 300.0, 5.9, 100.0, 55.0],
    'Length1': [23.2, 24.0, 23.9, 19.0, 20.0, 30.0, 35.0, 7.5, 15.0, 13.5],
    'Length2': [25.4, 26.3, 26.5, 21.0, 22.0, 32.3, 37.0, 8.4, 16.5, 14.7],
    'Length3': [30.0, 31.2, 31.1, 22.5, 23.5, 34.8, 40.0, 8.8, 18.2, 16.5],
    'Height': [11.52, 12.48, 12.37, 5.85, 6.11, 5.57, 7.21, 2.11, 4.01, 3.5],
    'Width': [4.02, 4.31, 4.69, 3.52, 3.72, 3.37, 4.56, 1.41, 2.82, 2.5]
}
df_fish = pd.DataFrame(fish_data)
df_fish.to_csv('/content/sample_data/Fish.csv', index=False)
print("Đã 'thả' cá vào file /content/sample_data/Fish.csv thành công!")

Đã 'thả' cá vào file /content/sample_data/Fish.csv thành công!


In [60]:
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

             Weight  Length1    Length2    Length3     Height  Width
Species                                                             
Bream    290.666667    23.70  26.066667  30.766667  12.123333  4.340
Parkki    55.000000    13.50  14.700000  16.500000   3.500000  2.500
Perch     52.950000    11.25  12.450000  13.500000   3.060000  2.115
Pike     250.000000    32.50  34.650000  37.400000   6.390000  3.965
Roach    135.000000    19.50  21.500000  23.000000   5.980000  3.620
Species
Bream     242.0
Parkki     55.0
Perch       5.9
Pike      200.0
Roach     120.0
Name: Weight, dtype: float64
Species  Height
Bream    11.52     242.0
         12.37     340.0
         12.48     290.0
Parkki   3.50       55.0
Perch    2.11        5.9
Name: Weight, dtype: float64


#TENSORFLOW


In [61]:
import tensorflow as tf
import numpy as np

In [62]:
# 0-chiều (scalar)
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
r1_float = tf.constant(1.12, tf.float32)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1); print(r1_float); print(r1_string)
# 1-chiều (vector)
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)
# 2-chiều (ma trận)
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)
# 3-chiều
rank_3_tensor = tf.constant([
  [[0,1,2,3,4],[5,6,7,8,9]],
  [[10,11,12,13,14],[15,16,17,18,19]],
  [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [63]:
# zeros
t_zero = tf.zeros(10);        print(t_zero)
t_2zero = tf.zeros([3,3]);    print(t_2zero)
t_3zero = tf.zeros([3,3,5]);  print(t_3zero)
# ones
t_one  = tf.ones(10);         print(t_one)
t_2one = tf.ones([3,3]);      print(t_2one)
t_3one = tf.ones([3,3,5]);    print(t_3one)
# fill (giá trị bất kỳ)
t_1 = tf.fill(3, 10);       print(t_1)
t_2 = tf.fill([3,3], 9);    print(t_2)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)
tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [64]:
# linspace — số phần tử cố định trong khoảng
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)
# range — bước nhảy delta
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)
range_tensor2 = tf.range(3.0, delta=0.5)
print(range_tensor2)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)
tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [65]:
# normal
rt = tf.random.normal([5]);    print(rt)
rt = tf.random.normal([3,3]);  print(rt)
# truncated_normal
rt = tf.random.truncated_normal([5]);   print(rt)
rt = tf.random.truncated_normal([3,2]); print(rt)
rt = tf.random.truncated_normal([3,2,2]); print(rt)
# uniform
rt = tf.random.uniform([5], minval=10, maxval=20);      print(rt)
rt = tf.random.uniform([3,2], minval=10, maxval=20);    print(rt)
rt = tf.random.uniform([3,2,5], minval=10, maxval=20);  print(rt)
# shuffle
rt = tf.random.uniform([5], minval=10, maxval=20)
print(rt)
print(tf.random.shuffle(rt))

tf.Tensor([ 0.6552718   0.97346    -0.7876494  -0.21647441 -0.32170162], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.9379691   0.5353197  -0.0854698 ]
 [ 1.160133   -1.4890803   0.53297776]
 [-0.4331171   0.4462577  -0.25413117]], shape=(3, 3), dtype=float32)
tf.Tensor([-0.470137   -0.07625341  0.20341863  1.5941997  -1.6538347 ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.9651496  -0.97322947]
 [ 0.30872002  0.30577755]
 [-0.13027914 -1.2337453 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[-0.3362416  -0.3783413 ]
  [ 0.6081403  -0.07600415]]

 [[-0.71722484  1.0959632 ]
  [-1.1184386  -0.10315644]]

 [[ 0.60396075  1.3262668 ]
  [-1.311209   -0.27228117]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor([14.742948 16.729311 15.818194 19.026722 10.245497], shape=(5,), dtype=float32)
tf.Tensor(
[[13.087655 12.473049]
 [17.029945 19.825865]
 [18.574116 10.765109]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[11.337757  10.258236  19.519823  16.23629   19.886276 ]
  [14.823301  18.364326  14.4